filetype plugin on
filetype indent on
colorscheme default
syntax on
set expandtab
set copyindent
set preserveindent
set softtabstop=2
set shiftwidth=2
set tabstop=2
set cinoptions=(0,u0,U0
set smartindent
set foldmethod=indent
