filetype plugin on
filetype indent on
" Commented out for now, finding a better color
"" colorscheme darkblue
"" colorscheme slate

" These settings are needed for the 'sierra' scheme
" to work properly
set t_Co=256
set background=dark
let g:sierra_Twilight = 1
colorscheme sierra

" Turn on syntax highlighting
syntax on

" Make tabs and indenting work better
set expandtab
set copyindent
set preserveindent
set softtabstop=2
set shiftwidth=2
set tabstop=2
set cinoptions=(0,u0,U0
set smartindent

" Turn on line folding, keying off of indents
set foldmethod=indent
