filetype plugin on
colorscheme default
syntax on
set expandtab
set copyindent
set preserveindent
set softtabstop=2
set shiftwidth=2
set tabstop=2
set cinoptions=(0,u0,U0
filetype indent on
set smartindent
